version: '3.8'

services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6099:6099"
    environment:
      - NAPCAT_GID=${NAPCAT_GID}
      - NAPCAT_UID=${NAPCAT_UID}
    restart: always
    volumes:
      - "./napcat/app/.config/QQ:/app/.config/QQ"
      - "./napcat/app/napcat:/app/napcat"
      - "./napcat/config:/app/napcat/config"
      - "/home/bot/app/scripts/WeatherSubscribe:/home/bot/app/scripts/WeatherSubscribe"
      - "/home/bot/app/scripts/ImageGenerate/output:/home/bot/app/scripts/ImageGenerate/output"
    